package com.cimc.senheyun.po;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class BsUserPo {
   
    private String pkUser;

    private String pkCompany;

    private String name;

    private Integer sex;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private String birthdate;

    private String phonenumber;

    private String accountnumber;

    private String password;

    private String passwordsalt;

    private String creator;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private String creatortime;

    private String modifier;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private String modifiedtime;

    private Integer enablestate;
    
    private String token;

    public String getPkUser() {
        return pkUser;
    }

    public void setPkUser(String pkUser) {
        this.pkUser = pkUser == null ? null : pkUser.trim();
    }

    public String getPkCompany() {
        return pkCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.pk_company
     *
     * @param pkCompany the value for bs_user.pk_company
     *
     * @mbg.generated
     */
    public void setPkCompany(String pkCompany) {
        this.pkCompany = pkCompany == null ? null : pkCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.name
     *
     * @return the value of bs_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.name
     *
     * @param name the value for bs_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.sex
     *
     * @return the value of bs_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.sex
     *
     * @param sex the value for bs_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.birthDate
     *
     * @return the value of bs_user.birthDate
     *
     * @mbg.generated
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.phoneNumber
     *
     * @return the value of bs_user.phoneNumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.phoneNumber
     *
     * @param phonenumber the value for bs_user.phoneNumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.accountNumber
     *
     * @return the value of bs_user.accountNumber
     *
     * @mbg.generated
     */
    public String getAccountnumber() {
        return accountnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.accountNumber
     *
     * @param accountnumber the value for bs_user.accountNumber
     *
     * @mbg.generated
     */
    public void setAccountnumber(String accountnumber) {
        this.accountnumber = accountnumber == null ? null : accountnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.password
     *
     * @return the value of bs_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.password
     *
     * @param password the value for bs_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.passwordSalt
     *
     * @return the value of bs_user.passwordSalt
     *
     * @mbg.generated
     */
    public String getPasswordsalt() {
        return passwordsalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.passwordSalt
     *
     * @param passwordsalt the value for bs_user.passwordSalt
     *
     * @mbg.generated
     */
    public void setPasswordsalt(String passwordsalt) {
        this.passwordsalt = passwordsalt == null ? null : passwordsalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.creator
     *
     * @return the value of bs_user.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.creator
     *
     * @param creator the value for bs_user.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.modifier
     *
     * @return the value of bs_user.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.modifier
     *
     * @param modifier the value for bs_user.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.modifiedtime
     *
     * @return the value of bs_user.modifiedtime
     *
     * @mbg.generated
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.enablestate
     *
     * @return the value of bs_user.enablestate
     *
     * @mbg.generated
     */
    public Integer getEnablestate() {
        return enablestate;
    }

    public String getBirthdate() {
		return birthdate;
	}

	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	public String getCreatortime() {
		return creatortime;
	}

	public void setCreatortime(String creatortime) {
		this.creatortime = creatortime;
	}

	public String getModifiedtime() {
		return modifiedtime;
	}

	public void setModifiedtime(String modifiedtime) {
		this.modifiedtime = modifiedtime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.enablestate
     *
     * @param enablestate the value for bs_user.enablestate
     *
     * @mbg.generated
     */
    public void setEnablestate(Integer enablestate) {
        this.enablestate = enablestate;
    }

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}
}