package com.cimc.senheyun.po;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class VdTokenPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_token.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_token.accessToken
     *
     * @mbg.generated
     */
    private String accesstoken;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private String validtime;

    


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_token.id
     *
     * @return the value of vd_token.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_token.id
     *
     * @param id the value for vd_token.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_token.accessToken
     *
     * @return the value of vd_token.accessToken
     *
     * @mbg.generated
     */
    public String getAccesstoken() {
        return accesstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_token.accessToken
     *
     * @param accesstoken the value for vd_token.accessToken
     *
     * @mbg.generated
     */
    public void setAccesstoken(String accesstoken) {
        this.accesstoken = accesstoken == null ? null : accesstoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_token.validTime
     *
     * @return the value of vd_token.validTime
     *
     * @mbg.generated
     */
    public String getValidtime() {
        return validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_token.validTime
     *
     * @param validtime the value for vd_token.validTime
     *
     * @mbg.generated
     */
    public void setValidtime(String validtime) {
        this.validtime = validtime;
    }
}