
package com.cimc.senheyun.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "iotDataService", targetNamespace = "http://action.web.iot_data_service.com", wsdlLocation = "http://iot.klha.net:8080/services/iotDataService?wsdl")
public class IotDataService
    extends Service
{

    private final static URL IOTDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException IOTDATASERVICE_EXCEPTION;
    private final static QName IOTDATASERVICE_QNAME = new QName("http://action.web.iot_data_service.com", "iotDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://iot.klha.net:8080/services/iotDataService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IOTDATASERVICE_WSDL_LOCATION = url;
        IOTDATASERVICE_EXCEPTION = e;
    }

    public IotDataService() {
        super(__getWsdlLocation(), IOTDATASERVICE_QNAME);
    }

    public IotDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IOTDATASERVICE_QNAME, features);
    }

    public IotDataService(URL wsdlLocation) {
        super(wsdlLocation, IOTDATASERVICE_QNAME);
    }

    public IotDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IOTDATASERVICE_QNAME, features);
    }

    public IotDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IotDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IotDataServicePortType
     */
    @WebEndpoint(name = "iotDataServiceHttpSoap11Endpoint")
    public IotDataServicePortType getIotDataServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://action.web.iot_data_service.com", "iotDataServiceHttpSoap11Endpoint"), IotDataServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IotDataServicePortType
     */
    @WebEndpoint(name = "iotDataServiceHttpSoap11Endpoint")
    public IotDataServicePortType getIotDataServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://action.web.iot_data_service.com", "iotDataServiceHttpSoap11Endpoint"), IotDataServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IOTDATASERVICE_EXCEPTION!= null) {
            throw IOTDATASERVICE_EXCEPTION;
        }
        return IOTDATASERVICE_WSDL_LOCATION;
    }

}
