
package com.cimc.senheyun.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "iotDataServicePortType", targetNamespace = "http://action.web.iot_data_service.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IotDataServicePortType {


    /**
     * 
     * @param param0
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GatewayData", action = "urn:GatewayData")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "GatewayData", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.GatewayData")
    @ResponseWrapper(localName = "GatewayDataResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.GatewayDataResponse")
    public String gatewayData(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2);

    /**
     * 
     * @param param0
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:updateGateway")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "updateGateway", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.UpdateGateway")
    @ResponseWrapper(localName = "updateGatewayResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.UpdateGatewayResponse")
    public String updateGateway(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2);

    /**
     * 
     * @param param0
     * @param param3
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GatewayHistory2", action = "urn:GatewayHistory2")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "GatewayHistory2", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.GatewayHistory2")
    @ResponseWrapper(localName = "GatewayHistory2Response", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.GatewayHistory2Response")
    public String gatewayHistory2(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2,
        @WebParam(name = "param3", targetNamespace = "http://action.web.iot_data_service.com")
        String param3);

    /**
     * 
     * @param param0
     * @param param1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:findAlert")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "findAlert", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.FindAlert")
    @ResponseWrapper(localName = "findAlertResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.FindAlertResponse")
    public String findAlert(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1);

    /**
     * 
     * @param param0
     * @param param1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:findChannelLimit")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "findChannelLimit", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.FindChannelLimit")
    @ResponseWrapper(localName = "findChannelLimitResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.FindChannelLimitResponse")
    public String findChannelLimit(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1);

    /**
     * 
     * @param param5
     * @param param0
     * @param param3
     * @param param4
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:ctrlChannel")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "ctrlChannel", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.CtrlChannel")
    @ResponseWrapper(localName = "ctrlChannelResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.CtrlChannelResponse")
    public String ctrlChannel(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2,
        @WebParam(name = "param3", targetNamespace = "http://action.web.iot_data_service.com")
        String param3,
        @WebParam(name = "param4", targetNamespace = "http://action.web.iot_data_service.com")
        String param4,
        @WebParam(name = "param5", targetNamespace = "http://action.web.iot_data_service.com")
        String param5);

    /**
     * 
     * @param param0
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:deletechannelLimit")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "deletechannelLimit", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.DeletechannelLimit")
    @ResponseWrapper(localName = "deletechannelLimitResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.DeletechannelLimitResponse")
    public String deletechannelLimit(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2);

    /**
     * 
     * @param param0
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:addGateway")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "addGateway", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.AddGateway")
    @ResponseWrapper(localName = "addGatewayResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.AddGatewayResponse")
    public String addGateway(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2);

    /**
     * 
     * @param param0
     * @param param1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GatewayList", action = "urn:GatewayList")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "GatewayList", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.GatewayList")
    @ResponseWrapper(localName = "GatewayListResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.GatewayListResponse")
    public String gatewayList(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1);

    /**
     * 
     * @param param5
     * @param param0
     * @param param3
     * @param param4
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sendCommand")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "sendCommand", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.SendCommand")
    @ResponseWrapper(localName = "sendCommandResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.SendCommandResponse")
    public String sendCommand(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2,
        @WebParam(name = "param3", targetNamespace = "http://action.web.iot_data_service.com")
        Integer param3,
        @WebParam(name = "param4", targetNamespace = "http://action.web.iot_data_service.com")
        Integer param4,
        @WebParam(name = "param5", targetNamespace = "http://action.web.iot_data_service.com")
        String param5);

    /**
     * 
     * @param param0
     * @param param3
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:chkSensorState")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "chkSensorState", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.ChkSensorState")
    @ResponseWrapper(localName = "chkSensorStateResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.ChkSensorStateResponse")
    public String chkSensorState(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2,
        @WebParam(name = "param3", targetNamespace = "http://action.web.iot_data_service.com")
        Integer param3);

    /**
     * 
     * @param param7
     * @param param5
     * @param param6
     * @param param0
     * @param param3
     * @param param4
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChartData", action = "urn:ChartData")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "ChartData", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.ChartData")
    @ResponseWrapper(localName = "ChartDataResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.ChartDataResponse")
    public String chartData(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2,
        @WebParam(name = "param3", targetNamespace = "http://action.web.iot_data_service.com")
        String param3,
        @WebParam(name = "param4", targetNamespace = "http://action.web.iot_data_service.com")
        String param4,
        @WebParam(name = "param5", targetNamespace = "http://action.web.iot_data_service.com")
        String param5,
        @WebParam(name = "param6", targetNamespace = "http://action.web.iot_data_service.com")
        String param6,
        @WebParam(name = "param7", targetNamespace = "http://action.web.iot_data_service.com")
        String param7);

    /**
     * 
     * @param param0
     * @param param1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurAllData", action = "urn:CurAllData")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "CurAllData", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.CurAllData")
    @ResponseWrapper(localName = "CurAllDataResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.CurAllDataResponse")
    public String curAllData(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1);

    /**
     * 
     * @param param0
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:addchannelLimit")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "addchannelLimit", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.AddchannelLimit")
    @ResponseWrapper(localName = "addchannelLimitResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.AddchannelLimitResponse")
    public String addchannelLimit(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2);

    /**
     * 
     * @param param0
     * @param param3
     * @param param4
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GatewayHistory", action = "urn:GatewayHistory")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "GatewayHistory", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.GatewayHistory")
    @ResponseWrapper(localName = "GatewayHistoryResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.GatewayHistoryResponse")
    public String gatewayHistory(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2,
        @WebParam(name = "param3", targetNamespace = "http://action.web.iot_data_service.com")
        String param3,
        @WebParam(name = "param4", targetNamespace = "http://action.web.iot_data_service.com")
        String param4);

    /**
     * 
     * @param param0
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:deleteGateway")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "deleteGateway", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.DeleteGateway")
    @ResponseWrapper(localName = "deleteGatewayResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.DeleteGatewayResponse")
    public String deleteGateway(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2);

    /**
     * 
     * @param param0
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:updatechannelLimit")
    @WebResult(targetNamespace = "http://action.web.iot_data_service.com")
    @RequestWrapper(localName = "updatechannelLimit", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.UpdatechannelLimit")
    @ResponseWrapper(localName = "updatechannelLimitResponse", targetNamespace = "http://action.web.iot_data_service.com", className = "com.iot_data_service.web.action.UpdatechannelLimitResponse")
    public String updatechannelLimit(
        @WebParam(name = "param0", targetNamespace = "http://action.web.iot_data_service.com")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://action.web.iot_data_service.com")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://action.web.iot_data_service.com")
        String param2);

}
